from .fr1_test import *
from .fr2_test import *
from .fr3_test import *
from .fr4_test import *
from .fr5_test import *
from .fr6_test import *
from .fr7_test import *
from .fr8_test import *
from .fr9_10_test import *
from .fr11_test import *
from .fr12_test import *
from .fr13_test import *
from .fr14_test import *
from .fr15_test import *